### ISSUE TITLE
how to Create a .env file with your database url.

### ISSUE THREAD

**Issue by SusLink0** [DxxxxY/R.A.T#1]
i cant understand how to do the step 3 of the setup

**Comment by DxxxxY** [comment]
basically, what you do is create a file named `.env` and you add a line like this:

```
DB=yourmongodburl
```

`dotenv`, allows you to use that as variables: for example `process.env.DB`

you could just replace `process.env.DB` by the mongodb url directly. this is just setup this way so you wont end up leaking your url.

**Comment by SusLink0** [comment]
can i use database url as discord webhook?

**Comment by SusLink0** [comment]
btw can u make a vid in vich u tell how to set this r.a.t up as i am still unable to do it

**Comment by DxxxxY** [comment]
umm... making a vid would be excessive as its kinda simple to setup. instead, tell me **where you are stuck/what you are unable to do or understand**

**Comment by sakuriaz** [comment]
Hi, can you add me on discord Hereafter#6615 and show me how to setup? I'd appreciate it!!

**Comment by 7vaze** [comment]
i also dont undestand step 3 can you help me

**Comment by DxxxxY** [comment]
> basically, what you do is create a file named `.env` and you add a line like this:
> 
> ```
> DB=yourmongodburl
> ```
> 
> `dotenv`, allows you to use that as variables: for example `process.env.DB`
> 
> you could just replace `process.env.DB` by the mongodb url directly. this is just setup this way so you wont end up leaking your url. 
>

**Comment by DxxxxY** [comment]
i might make a demo video later but currently have finals and lots of assignment submissions

**Comment by hookerf** [comment]
hi looking for video or a contact to reach u please

**Comment by DxxxxY** [comment]
In case you still need the video, I just published it: https://www.youtube.com/watch?v=JWoBSp8XU_8&ab_channel=DxxxxY. Took me a while because of finals.
