### ISSUE TITLE
Discord Token is invalid

### ISSUE THREAD

**Issue by Doppelbemme** [DxxxxY/R.A.T#10]
Hey there,
I tried out the function you use to grab the discord token.
However when I try to login via Chrome using the token the function returns it isnt working.

**Comment by DxxxxY** [comment]
Probably an issue on your end. iirc discord patched that function and you have to use another method to login with tokens.

**Comment by Doppelbemme** [comment]
> Probably an issue on your end. iirc discord patched that function and you have to use another method to login with tokens.

Oh okay didnt knew about that one.
Do you currently know another way to login with the token?

**Comment by DxxxxY** [comment]
Fixed in 6e868d8.
