### ISSUE TITLE
How to I login with that 

### ISSUE THREAD

**Issue by eyal0203** [DxxxxY/R.A.T#12]
"Apparently switching the feather or essential files with yours grants you infinite access to their account thanks to the refreshToken. (Unconfirmed, ask Shlost#5052)"
I get info not files
how do i login with that (Refresh token)
Also I don't get discord tokens.

**Comment by DxxxxY** [comment]
You get the whole content of the file. Find where it comes from (Hint: check rat class where it grabs those files) and replace your file content with that. You might want to make a backup of the old file. Also, I know there's an issue with discord tokens, I'm not sure what causes it though, if you can find a better way to get them don't hesitate to open an issue or a PR.

**Comment by eyal0203** [comment]
> You get the whole content of the file. Find where it comes from (Hint: check rat class where it grabs those files) and replace your file content with that. You might want to make a backup of the old file. Also, I know there's an issue with discord tokens, I'm not sure what causes it though, if you can find a better way to get them don't hesitate to open an issue or a PR.

Thanks for the fast answer I will try that now
