### ISSUE TITLE
Could it be updated to 1.19?

### ISSUE THREAD

**Issue by Jinomee** [DxxxxY/R.A.T#19]
Title. Tysm

**Comment by EssentialModDevelopment** [comment]
Would be useful for grabbing discord also ive played on servers where people who have quit skyblock play and i just say can u test my health tags mod or smth. It would be useful

**Comment by Co18** [comment]
nahh bro aint no way nahhhhh nahhhhh nahhhhh naming your github essential mod development ???? ? ? ??  and asking if its for 1.19 nahhhh broooo noo aint no way stuff aint that cheap these days stooppppp its nahhhhh bruhuuhuhorooooo

**Comment by Co18** [comment]
ops switched to speakin black for a secend

**Comment by Joshua11TheHacker** [comment]
> nahh bro aint no way nahhhhh nahhhhh nahhhhh naming your github essential mod development ???? ? ? ?? and asking if its for 1.19 nahhhh broooo noo aint no way stuff aint that cheap these days stooppppp its nahhhhh bruhuuhuhorooooo

cmon dude let this man rat his mods in peace 🙌

**Comment by Joshua11TheHacker** [comment]
he will get so many discord tokens

**Comment by Joshua11TheHacker** [comment]
frfr

**Comment by TheDingOfTheHud** [comment]
i mean you can trick people into thinking its some moddpack for like 1.19 and 1.12.2. I was gonna do this to my guild and be like anyone wanna play on my moddedd server and just have the modpack include the rat

**Comment by 9001k** [comment]
cheater get ban

**Comment by 9001k** [comment]
fr

**Comment by BattleB0t** [comment]
You could update the 1.18 branch easily (https://github.com/DxxxxY/R.A.T/tree/1.18)

**Comment by EssentialModDevelopment** [comment]
> i mean you can trick people into thinking its some moddpack for like 1.19 and 1.12.2. I was gonna do this to my guild and be like anyone wanna play on my moddedd server and just have the modpack include the rat

My method get them to play a lucky blocks and say 50m reward for winner

**Comment by 9001k** [comment]
niggers

**Comment by Joshua11TheHacker** [comment]
> niggers

🤓

**Comment by 9001k** [comment]
ok nigga joshua

**Comment by Joshua11TheHacker** [comment]
> ok nigga joshua

🤓

**Comment by 9001k** [comment]
gn dxxxxy

**Comment by smhMatthew** [comment]
Could somebody help me to set it up?
Discord:Smh_mthew#9339
