### ISSUE TITLE
Heroku App Sleeping

### ISSUE THREAD

**Issue by StarQuery** [DxxxxY/R.A.T#4]
Is there any problem for heroku app sleeping should i change the procfile web to worker to make it stay alive for all the time or sleeping is fine

About sleeping: would it make the game go no response screen while loading the mod or no?

**Comment by DxxxxY** [comment]
You should leave it to web. Worker dynos do not have routing and your server could technically not be able to receive requests. The whole mod's preInit() is on another thread, which should not pause the main thread.

**Comment by DxxxxY** [comment]
Then again, I never quite tested it. You can try it yourself and open an issue if something wrong does occur.
