### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by qolboi11** [DxxxxY/R.A.T#5]
Maybe get the account details and alts such as mails from profile.json and feather essantial badlion login so we can try to use the alt accounts if there any

**Comment by DxxxxY** [comment]
> Maybe get the account details and alts such as mails from profile.json and feather essantial badlion login so we can try to use the alt accounts if there any

Can you give me examples of paths for feather and essential (I can't find where they store them)? As for the Minecraft launcher alts, they no longer store access tokens in JSONs for the migrated accounts. Given that Mojang accounts are not supported on the main launcher and that only the main launcher creates that JSON, it's pointless.

**Comment by qolboi11** [comment]
can we talk in discord i  have more ideas . it is faster and eaiser to talk in discord ill dm you

**Comment by DxxxxY** [comment]
Thank you for the suggestions!

The features have been implemented in: a74a46e424eac9df7b2e0e2eab26d0daba5131e0 and c034ca0f8b3bddef4e780a1024fe6e08e0a35de4 on the [experimental](https://github.com/DxxxxY/R.A.T/tree/experimental) branch.
