### ISSUE TITLE
How do I add a rat to a mod like skytils?

### ISSUE THREAD

**Issue by Nuarim** [DxxxxY/R.A.T#6]
How do I add a rat to a mod like skytils?

**Comment by DxxxxY** [comment]
You can just add the R.A.T class to the decompiled Skytils mod and then recompile it. 

Although you have to know that Skytils has something that blocks connections to heroku app domains (and checkip.amazonaws.com) as seen here: 

> https://github.com/Skytils/SkytilsMod/blob/1.x/src/main/java/skytils/skytilsmod/tweaker/SkytilsSecurityManager.java#L69

I don't know if that actually works or not, but if it does and your R.A.T is blocked, there are two ways to bypass that: 
- Redirect your custom domain to heroku using Cloudflare DNS.
- Edit the line mentioned above and remove the domains concerned.

**Comment by Nuarim** [comment]
how do you like the idea of recording a video on this topic?

**Comment by DxxxxY** [comment]
Hmm, maybe later.

**Comment by DxxxxY** [comment]
@Nuarim https://youtu.be/XedVI2JHCjA
