### ISSUE TITLE
PS D:\Project\R.A.T\server> npm i error

### ISSUE THREAD

**Issue by Vensentent** [DxxxxY/R.A.T#7]
PS D:\Project\R.A.T\server> npm i
npm : Имя "npm" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, после чего повторите попытку.
строка:1 знак:1
+ npm i
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DxxxxY** [comment]
This project runs on node.js so make sure you install it correctly.

https://nodejs.org/en/
